name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Setup-Bun:
    uses: ./.github/workflows/bun.yml
  Lint:
    runs-on: ubuntu-latest
    needs: Setup-Bun
    steps:
      - name: Lint code
        run: bun lint:fix
  Unit-Tests:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Execute Unit tests
        run: bun test:unit
  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: Unit-Tests
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
